
public enum MessageType {
	STATION_3_BLUE_BLOCK_DROPPED_OFF,
	STATION_1_RED_BLOCK_DROPPED_OFF,
	STATION_2_BLUE_BLOCK_DROPPED_OFF,
	STATION_2_RED_BLOCK_DROPPED_OFF,
	STATION_2_DONE,
	ZONE_1_LOCKED,
	ZONE_1_UNLOCKED,
	ZONE_2_1_LOCKED,
	ZONE_2_1_UNLOCKED,
	ZONE_2_2_LOCKED,
	ZONE_2_2_UNLOCKED,
	ZONE_3_LOCKED,
	ZONE_3_UNLOCKED,
	STATION_1_FIRST_ROW_CLEAR,
	STATION_3_FIRST_ROW_CLEAR
}